### ISSUE TITLE
Create inital tile system

### ISSUE THREAD

**Issue by ProfessorAkram** [csg-utulsa/CCUS#1]

**Comment by Doggitoz** [comment]
<img width="1415" alt="TilePrefab" src="https://github.com/csg-utulsa/CCUS/assets/48357584/03946ce0-0d0f-45c1-a6ad-fa44eeb61da7">
<img width="1269" alt="Game Overview" src="https://github.com/csg-utulsa/CCUS/assets/48357584/b54c7d40-a1bc-417a-a70e-36fb091d9a34">

**Comment by ProfessorAkram** [comment]
done
