### ISSUE TITLE
Neutral/Natural Tiles Modeled

### ISSUE THREAD

**Issue by ProfessorAkram** [csg-utulsa/CCUS#3]

**Comment by TheOneShrub** [comment]
[PrototypeTiles.zip](https://github.com/csg-utulsa/CCUS/files/11889550/PrototypeTiles.zip)

**Comment by TheOneShrub** [comment]
[WorkingTiles.zip](https://github.com/csg-utulsa/CCUS/files/12114891/WorkingTiles.zip)
