### ISSUE TITLE
Level Outline

### ISSUE THREAD

**Issue by ProfessorAkram** [csg-utulsa/CCUS#4]
Create a basic level outline for the game

**Comment by TheOneShrub** [comment]
**rules:**
-1 contract per level  (for prototype)
-limited tiles per level
-limited tile items per contract
-reset button always available 

**UI:**
Carbon level
Carbon storage level

**Level layout:**
SETUP
empty plane full of water tiles
Set carbon level
contract is assigned
inventory of tiles opens
tile limit and progress towards hitting limit visible at this stage
confirmation button available at anytime to continue to placing tile items (green ok button)
item inventory opens for player
player can place items according to item limit and $$$ budget
(this is main part, nuance of passing time and $$$ income TBD)
Player hits button to test simulation and see whether or not they achieved contract
player hits reset or wins level
